name: pnpm Example Workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build and deploy
      run: pnpm run build
    - name: Deploy Storybook
      working-directory: ./packages/docs
      run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
      env:
        GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}