name: Deploy docs
run-name: ${{ github.actor }} is deploying out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
       

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with: 
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml' 

      - name: Install dependencies
        run: pnpm install

      - run: pnpm run build
        env:
          TURBO_TOKEN: dnNwOtihBaUESHRyEjFHG9Fc
          TURBO_TEAM: 90srehem
      - name: Deploy storybook
        working-directory: ./packages/docs
        run: pnpm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}