name: Deploy docs
run-name: ${{ github.actor }} is deploying out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with: 
          version: 7

      - name: Install dependencies
        run: pnpm install

      - run: pnpm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: pnpm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}